sudo: false
language: node_js
env:
  - CXX="ccache g++-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

    packages:
    - libfuse-dev
    - fuse
    - build-essential
    - pkg-config
    - gcc-4.8
    - g++-4.8

cache: ccache

node_js:
  - "0.10"
  - "0.12"
  - "iojs-1"
  - "iojs-2"
  - "iojs-3"
  - "4"
  - "5"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/58c9d92f0d5882f60391
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - $CXX --version
  - npm install npm
  - mv node_modules npm
  - npm/.bin/npm --version  
  - npm/.bin/npm install -g node-gyp-install
  - npm/.bin/npm install -g mocha
  - node-gyp-install
  - wget http://downloads.sourceforge.net/project/fuse/fuse-2.X/2.9.4/fuse-2.9.4.tar.gz
  - tar xf fuse-2.9.4.tar.gz
  - mkdir include
  - cp fuse-2.9.4/include/*.h include

install:
  - npm/.bin/npm install

